POST http://localhost:8080/blogposts
Content-Type: application/json

{
  "userId": 1,
  "titleText": "Another Title",
  "bodyText": "Another post body",
  "date": null,
  "updateDate": null
}
###
DELETE http://localhost:8080/blogposts/2

###
PUT http://localhost:8080/blogposts/2
Content-Type: application/json

{
  "email": "abc@aol.com",
  "password": "pass",
  "firstName": "1",
  "lastName": "2"
}
###